import jsPDF from "jspdf";

// ─── Brand constants ────────────────────────────────────────────────────────
const C = {
  indigo: [53, 37, 205] as const,
  indigoLight: [87, 68, 255] as const,
  dark: [13, 12, 34] as const,
  emerald: [16, 185, 129] as const,
  amber: [245, 158, 11] as const,
  purple: [168, 85, 247] as const,
  red: [239, 68, 68] as const,
  muted: [107, 114, 128] as const,
  border: [229, 231, 235] as const,
  bg: [248, 249, 252] as const,
  white: [255, 255, 255] as const,
  black: [0, 0, 0] as const,
};

// A4 page metrics (mm)
const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN = 18;
const CONTENT_W = PAGE_W - MARGIN * 2;
const HEADER_H = 14;
const FOOTER_H = 12;
const CONTENT_TOP = MARGIN + HEADER_H + 6;
const CONTENT_BOTTOM = PAGE_H - FOOTER_H - 6;

// ─── Helpers ────────────────────────────────────────────────────────────────
function rgb(doc: jsPDF, color: readonly [number, number, number]) {
  doc.setTextColor(color[0], color[1], color[2]);
}

function fill(doc: jsPDF, color: readonly [number, number, number]) {
  doc.setFillColor(color[0], color[1], color[2]);
}

function stroke(doc: jsPDF, color: readonly [number, number, number]) {
  doc.setDrawColor(color[0], color[1], color[2]);
}

function scoreColor(score: number): readonly [number, number, number] {
  if (score >= 80) return C.emerald;
  if (score >= 60) return C.indigo;
  if (score >= 40) return C.amber;
  return C.red;
}

function scoreLabel(score: number): string {
  if (score >= 80) return "Excellent";
  if (score >= 60) return "Good";
  if (score >= 40) return "Fair";
  return "Poor";
}

function wrapText(doc: jsPDF, text: string, maxWidth: number): string[] {
  return doc.splitTextToSize(text, maxWidth);
}

// ─── Page chrome ─────────────────────────────────────────────────────────────
function drawHeader(doc: jsPDF, pageNum: number, total: number) {
  // Brand bar
  fill(doc, C.indigo);
  doc.rect(0, 0, PAGE_W, HEADER_H, "F");

  // "CLARIVA" logo text
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  rgb(doc, C.white);
  doc.text("CLARIVA", MARGIN, 9.5);

  // Subtitle right
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.text("Idea Analysis Report", PAGE_W - MARGIN, 9.5, { align: "right" });

  // Page indicator
  doc.setFontSize(6.5);
  rgb(doc, [200, 200, 230]);
  doc.text(`Page ${pageNum} of ${total}`, PAGE_W / 2, 9.5, { align: "center" });
}

function drawFooter(doc: jsPDF, ideaTitle: string) {
  const y = PAGE_H - FOOTER_H;

  // Top line
  stroke(doc, C.border);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);

  // Watermark (centered, light)
  doc.setFont("helvetica", "italic");
  doc.setFontSize(6.5);
  doc.setTextColor(180, 180, 200);
  doc.text("Generated by Clariva — clariva.app", PAGE_W / 2, y + 4.5, {
    align: "center",
  });

  // Idea title (left, truncated)
  const truncated =
    ideaTitle.length > 50 ? ideaTitle.slice(0, 47) + "…" : ideaTitle;
  doc.setFontSize(6);
  doc.setTextColor(160, 160, 180);
  doc.text(truncated, MARGIN, y + 4.5);

  // Date right
  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
  doc.text(dateStr, PAGE_W - MARGIN, y + 4.5, { align: "right" });
}

// ─── Score bar ───────────────────────────────────────────────────────────────
function drawScoreBar(
  doc: jsPDF,
  label: string,
  score: number,
  x: number,
  y: number,
  barW: number,
): number {
  const barH = 3.5;
  const rowH = 10;

  // Label
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  rgb(doc, C.dark);
  doc.text(label, x, y + 5);

  // Score value
  const color = scoreColor(score);
  rgb(doc, color);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text(`${score}/100`, x + barW, y + 5, { align: "right" });

  // Track background
  fill(doc, C.border);
  stroke(doc, C.border);
  doc.roundedRect(x, y + 6, barW, barH, 1, 1, "F");

  // Filled bar
  const fillW = Math.max(2, (score / 100) * barW);
  fill(doc, color);
  doc.roundedRect(x, y + 6, fillW, barH, 1, 1, "F");

  return rowH;
}

// ─── Section header ──────────────────────────────────────────────────────────
function drawSectionHeader(
  doc: jsPDF,
  title: string,
  y: number,
  emoji?: string,
): number {
  // Accent bar
  fill(doc, C.indigo);
  doc.rect(MARGIN, y, 2.5, 7, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  rgb(doc, C.dark);
  doc.text((emoji ? emoji + " " : "") + title, MARGIN + 5, y + 5.5);

  return 12;
}

// ─── Insight items ───────────────────────────────────────────────────────────
function drawInsightItem(
  doc: jsPDF,
  item: { title: string; desc: string },
  x: number,
  y: number,
  maxW: number,
  color: readonly [number, number, number],
): number {
  // Bullet dot
  fill(doc, color);
  doc.circle(x + 2, y + 2.5, 1.2, "F");

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  rgb(doc, C.dark);
  doc.text(item.title, x + 6, y + 3.5);

  // Description (wrapped)
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  rgb(doc, C.muted);
  const lines = wrapText(doc, item.desc, maxW - 6);
  doc.text(lines, x + 6, y + 8);

  return 6 + lines.length * 4 + 3; // padding
}

// ─── Card background ─────────────────────────────────────────────────────────
function drawCard(doc: jsPDF, x: number, y: number, w: number, h: number) {
  fill(doc, C.bg);
  stroke(doc, C.border);
  doc.setLineWidth(0.3);
  doc.roundedRect(x, y, w, h, 2, 2, "FD");
}

// ─── Main export function ─────────────────────────────────────────────────────
export interface PdfExportIdea {
  title: string;
  description: string;
  domain: string;
  createdAt: string;
  analysis: {
    overallScore?: number | null;
    feasibilityScore?: number | null;
    uniquenessScore?: number | null;
    impactScore?: number | null;
    innovationScore?: number | null;
    verdictSummary?: string | null;
    strengths?: Array<{ title: string; desc: string }> | null;
    weaknesses?: Array<{ title: string; desc: string }> | null;
    risks?: Array<{ title: string; desc: string }> | null;
    suggestions?: Array<{ title: string; desc: string }> | null;
    techStack?: string[] | null;
    githubRepos?: Array<{
      name: string;
      org: string;
      stars: number;
      desc: string;
      lang: string;
      url: string;
    }> | null;
    marketContext?: string | null;
  };
}

export function exportIdeaAnalysisPdf(idea: PdfExportIdea): void {
  const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });
  const a = idea.analysis;

  // We'll collect all pages' worth of content, then go back and draw chrome
  // Actually we draw inline and add pages as needed.

  let pageNum = 1;

  const newPage = () => {
    doc.addPage();
    pageNum++;
    return CONTENT_TOP;
  };

  const ensureSpace = (y: number, needed: number): number => {
    if (y + needed > CONTENT_BOTTOM) {
      return newPage();
    }
    return y;
  };

  // ── Page 1 ──────────────────────────────────────────────────────────────

  let y = CONTENT_TOP;

  // ── Idea header ────────────────────────────────────────────────────────
  // Domain badge
  const domainText = (idea.domain || "General").toUpperCase();
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  fill(doc, [237, 233, 254]); // light indigo bg
  stroke(doc, [196, 181, 253]); // indigo border
  doc.setLineWidth(0.3);
  const domainW = doc.getTextWidth(domainText) + 6;
  doc.roundedRect(MARGIN, y, domainW, 5.5, 1, 1, "FD");
  rgb(doc, C.indigo);
  doc.text(domainText, MARGIN + 3, y + 3.8);

  y += 8;

  // Idea title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  rgb(doc, C.dark);
  const titleLines = wrapText(doc, idea.title, CONTENT_W);
  doc.text(titleLines, MARGIN, y + 6);
  y += titleLines.length * 8 + 4;

  // Submitted date
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  rgb(doc, C.muted);
  const dateStr = new Date(idea.createdAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.text(`Submitted: ${dateStr}`, MARGIN, y);
  y += 8;

  // Separator line
  stroke(doc, C.border);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 6;

  // Description
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  rgb(doc, C.dark);
  const descLines = wrapText(doc, idea.description, CONTENT_W);
  const descH = descLines.length * 4.5 + 6;
  y = ensureSpace(y, descH);
  drawCard(doc, MARGIN, y, CONTENT_W, descH);
  doc.text(descLines, MARGIN + 4, y + 4.5);
  y += descH + 8;

  // ── Score section ──────────────────────────────────────────────────────
  y = ensureSpace(y, 60);
  y += drawSectionHeader(doc, "Analysis Scores", y);

  const overallScore = a.overallScore ?? 0;
  const sl = {
    label: scoreLabel(overallScore),
    color: scoreColor(overallScore),
  };

  // Overall score card (left column)
  const colW = (CONTENT_W - 8) / 2;
  const scoreCardH = 44;
  drawCard(doc, MARGIN, y, colW, scoreCardH);

  // Big score number
  doc.setFont("helvetica", "bold");
  doc.setFontSize(36);
  rgb(doc, sl.color);
  doc.text(String(overallScore), MARGIN + colW / 2, y + 18, {
    align: "center",
  });

  // "/100" suffix
  doc.setFontSize(10);
  rgb(doc, C.muted);
  doc.text("/100", MARGIN + colW / 2 + 8, y + 18, { align: "left" });

  // Label badge
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  rgb(doc, sl.color);
  doc.text(sl.label, MARGIN + colW / 2, y + 26, { align: "center" });

  // "Overall Verdict" subtitle
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  rgb(doc, C.muted);
  doc.text("OVERALL VERDICT", MARGIN + colW / 2, y + 32, { align: "center" });

  // Sub-score bars (right column)
  const barsX = MARGIN + colW + 8;
  const barsW = colW;
  drawCard(doc, barsX, y, barsW, scoreCardH);

  let barY = y + 4;
  const barInnerW = barsW - 8;
  if (a.feasibilityScore != null)
    barY += drawScoreBar(
      doc,
      "Feasibility",
      a.feasibilityScore,
      barsX + 4,
      barY,
      barInnerW,
    );
  if (a.uniquenessScore != null)
    barY += drawScoreBar(
      doc,
      "Uniqueness",
      a.uniquenessScore,
      barsX + 4,
      barY,
      barInnerW,
    );
  if (a.impactScore != null)
    barY += drawScoreBar(
      doc,
      "Impact",
      a.impactScore,
      barsX + 4,
      barY,
      barInnerW,
    );
  if (a.innovationScore != null)
    barY += drawScoreBar(
      doc,
      "Innovation",
      a.innovationScore,
      barsX + 4,
      barY,
      barInnerW,
    );

  y += scoreCardH + 8;

  // ── Verdict summary ────────────────────────────────────────────────────
  if (a.verdictSummary) {
    y = ensureSpace(y, 30);
    y += drawSectionHeader(doc, "Engine Verdict", y);
    const verdictLines = wrapText(doc, a.verdictSummary, CONTENT_W - 8);
    const verdictH = verdictLines.length * 4.5 + 8;
    drawCard(doc, MARGIN, y, CONTENT_W, verdictH);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    rgb(doc, C.dark);
    doc.text(verdictLines, MARGIN + 4, y + 5);
    y += verdictH + 8;
  }

  // ── Insights ───────────────────────────────────────────────────────────
  const insightSections: Array<{
    title: string;
    items: Array<{ title: string; desc: string }> | null | undefined;
    color: readonly [number, number, number];
  }> = [
    { title: "Strengths", items: a.strengths, color: C.emerald },
    { title: "Weaknesses", items: a.weaknesses, color: C.amber },
    { title: "Market Risks", items: a.risks, color: C.red },
    { title: "Strategic Pivots", items: a.suggestions, color: C.indigo },
  ];

  for (const section of insightSections) {
    if (!section.items || section.items.length === 0) continue;

    y = ensureSpace(y, 20);
    y += drawSectionHeader(doc, section.title, y);

    for (const item of section.items) {
      const itemLines = wrapText(doc, item.desc, CONTENT_W - 8);
      const itemH = 6 + itemLines.length * 4 + 5;
      y = ensureSpace(y, itemH);
      drawInsightItem(doc, item, MARGIN, y, CONTENT_W, section.color);
      y += itemH;
    }
    y += 4;
  }

  // ── Tech Stack ─────────────────────────────────────────────────────────
  if (a.techStack && a.techStack.length > 0) {
    y = ensureSpace(y, 24);
    y += drawSectionHeader(doc, "Recommended Tech Stack", y);

    let tagX = MARGIN;
    const tagY = y;
    const tagH = 6;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);

    let maxTagH = tagH + 2;
    for (const tech of a.techStack) {
      const tagW = doc.getTextWidth(tech) + 8;
      if (tagX + tagW > PAGE_W - MARGIN) {
        tagX = MARGIN;
        y += tagH + 3;
        maxTagH += tagH + 3;
      }
      fill(doc, [237, 233, 254]);
      stroke(doc, [196, 181, 253]);
      doc.setLineWidth(0.3);
      doc.roundedRect(tagX, y, tagW, tagH, 1.5, 1.5, "FD");
      rgb(doc, C.indigo);
      doc.text(tech, tagX + 4, y + 4.3);
      tagX += tagW + 3;
    }
    y += tagH + 10;
  }

  // ── GitHub Repos ───────────────────────────────────────────────────────
  if (a.githubRepos && a.githubRepos.length > 0) {
    y = ensureSpace(y, 20);
    y += drawSectionHeader(doc, "Relevant Prior Art (GitHub)", y);

    for (const repo of a.githubRepos) {
      const repoDescLines = wrapText(doc, repo.desc || "", CONTENT_W - 8);
      const repoH = 6 + repoDescLines.length * 4 + 12;
      y = ensureSpace(y, repoH);
      drawCard(doc, MARGIN, y, CONTENT_W, repoH);

      // Repo name (clickable link)
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      rgb(doc, C.indigo);
      const repoName = `${repo.org}/${repo.name}`;
      doc.textWithLink(repoName, MARGIN + 4, y + 5, { url: repo.url });

      // Stars
      const starsStr =
        repo.stars >= 1000
          ? `★ ${(repo.stars / 1000).toFixed(1)}k`
          : `★ ${repo.stars}`;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      rgb(doc, C.muted);
      doc.text(starsStr, PAGE_W - MARGIN - 4, y + 5, { align: "right" });

      // Lang badge
      doc.setFontSize(7);
      rgb(doc, C.indigo);
      doc.text(repo.lang || "", MARGIN + 4, y + repoH - 4);

      // Description
      if (repoDescLines.length > 0) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(7.5);
        rgb(doc, C.muted);
        doc.text(repoDescLines, MARGIN + 4, y + 10);
      }

      y += repoH + 4;
    }
    y += 4;
  }

  // ── Market Context ─────────────────────────────────────────────────────
  if (a.marketContext) {
    y = ensureSpace(y, 20);
    y += drawSectionHeader(doc, "Market Context", y);
    const mcLines = wrapText(doc, a.marketContext, CONTENT_W - 8);
    const mcH = mcLines.length * 4.5 + 8;
    y = ensureSpace(y, mcH);
    drawCard(doc, MARGIN, y, CONTENT_W, mcH);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    rgb(doc, C.dark);
    doc.text(mcLines, MARGIN + 4, y + 5);
    y += mcH + 8;
  }

  // ── Draw chrome on all pages ────────────────────────────────────────────
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    drawHeader(doc, p, totalPages);
    drawFooter(doc, idea.title);
  }

  // ── Save ────────────────────────────────────────────────────────────────
  const safeTitle = idea.title
    .replace(/[^a-z0-9]/gi, "-")
    .toLowerCase()
    .slice(0, 40);
  doc.save(`clariva-analysis-${safeTitle}.pdf`);
}
