// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/clariva/Auth.tsx": () => import("../components/mockups/clariva/Auth.tsx"),
  "./components/mockups/clariva/Compare.tsx": () => import("../components/mockups/clariva/Compare.tsx"),
  "./components/mockups/clariva/Dashboard.tsx": () => import("../components/mockups/clariva/Dashboard.tsx"),
  "./components/mockups/clariva/Results.tsx": () => import("../components/mockups/clariva/Results.tsx"),
  "./components/mockups/clariva/Submit.tsx": () => import("../components/mockups/clariva/Submit.tsx")
};
